# Generated by Django 5.0 on 2025-01-02 20:09

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(max_length=255)),
                ("remote", models.BooleanField(default=False)),
                ("salary_min", models.FloatField(blank=True, null=True)),
                ("salary_max", models.FloatField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=10)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("telegram_message_id", models.BigIntegerField()),
                ("telegram_channel_id", models.BigIntegerField()),
                ("telegram_channel_name", models.CharField(max_length=255)),
                ("telegram_message_date", models.DateTimeField()),
                ("telegram_views", models.IntegerField(blank=True, null=True)),
                ("telegram_forwards", models.IntegerField(blank=True, null=True)),
                ("telegram_raw_text", models.TextField()),
                ("telegram_metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-telegram_message_date"],
                "indexes": [
                    models.Index(
                        fields=["-telegram_message_date"],
                        name="job_scraper_telegra_5683ec_idx",
                    ),
                    models.Index(
                        fields=["telegram_channel_name"],
                        name="job_scraper_telegra_c5dbc6_idx",
                    ),
                    models.Index(
                        fields=["remote"], name="job_scraper_remote_14bf34_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["channel_name"],
                "indexes": [
                    models.Index(
                        fields=["channel_name"], name="job_scraper_channel_dae184_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="job_scraper_is_acti_df04c2_idx"
                    ),
                ],
            },
        ),
    ]
