# Generated by Django 4.2.17 on 2025-01-02 20:57

from django.db import migrations, models
import json

def convert_array_to_json(apps, schema_editor):
    Job = apps.get_model('job_scraper', 'Job')
    db_alias = schema_editor.connection.alias
    for job in Job.objects.using(db_alias).all():
        if job.categories is not None:
            # Convert array to JSON list
            job.categories = json.dumps(list(job.categories))
            job.save()

class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramchannel',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='telegramchannel',
            name='job_scraper_channel_dae184_idx',
        ),
        migrations.RemoveIndex(
            model_name='telegramchannel',
            name='job_scraper_is_acti_df04c2_idx',
        ),
        # First convert categories to text
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        # Run the conversion function
        migrations.RunPython(convert_array_to_json),
        # Then convert to JSONField
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='telegram_forwards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='telegram_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='telegram_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
