# Generated by Django 4.2.17 on 2025-01-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="is_template",
            field=models.BooleanField(
                default=False,
                help_text="Mark this resume as a template for generating other resumes",
            ),
        ),
    ]
