# Generated by Django 4.2.17 on 2025-01-06 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scraper", "0002_resume_is_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "tex"]
                    )
                ],
            ),
        ),
    ]
