# Generated by Django 4.2.17 on 2025-01-08 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scraper", "0003_allow_tex_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="extracted_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="job",
            name="processed_by_llm",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["tex"]
                    )
                ],
            ),
        ),
    ]
