# Generated by Django 4.2.17 on 2025-01-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0004_job_extracted_data_job_processed_by_llm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruiter_contact',
            field=models.CharField(blank=True, help_text='Contact information for the recruiter (email, telegram, etc.)', max_length=255, null=True),
        ),
    ]
